### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Brightttttt** [ScottUK/ladojrp-issues#1]
Allow LEO to use flares for things like roadblocks and not only for giving AO a place to land. IRL they would block roads with flares they have in the back of their car.

**Comment by ScottUK** [comment]
This might be more of a top 5 thing, if you could get to them about this. :D

**Comment by Brightttttt** [comment]
> This might be more of a top 5 thing, if you could get to them about this. :D

Kinda yes and no as it states in the rules that LEO can only use flares to advise locations for a helicopter. But I will request it to them!
