### ISSUE TITLE
LEO Belts Returning to the EUP???

### ISSUE THREAD

**Issue by itsCrummy** [ScottUK/ladojrp-issues#10]
**Describe the feature you'd like implemented**
Before the New EUP was put in the server we had a ton of LEO belts to choose from, But since the NEW EUP was put in, all the Belts that were given to LEO have been removed. The New Belts were put in in September 2021

**Additional context**
Here is the 2 announcements that showed off the Belts / When Execs (Drake) told us about the New Belts in Both LEO TOP 4 Private Announcement chats.
https://discord.com/channels/721156947495354428/721173536265207808/888784094807339048

https://discord.com/channels/721156947495354428/721157721654689802/888939187175297084

**Comment by LADOJRP-Mello** [comment]
+1

**Comment by LadojrpAustin** [comment]
Hello Crummy this is Austin with the LADOJRP Suggestions team

Thank you for this suggestion and it will be taken under consideration

I am sorry for the late response, but the LEO EUP Already has come in so this suggestion will sadly be denied.
