### ISSUE TITLE
Cops seeing /bm

### ISSUE THREAD

**Issue by Brightttttt** [ScottUK/ladojrp-issues#100]
Make it so cops on duty can see /bm's this is for the purpose of that we have detective subdivisions and they have burner laptops they can use to get on the black market realistically. I know it was prob removed for people metagaming but for those officers who meta game should be punished. If this is gonna be removed It's just gonna give detectives even less RP than they have.  Cops not being able to see /bm is unrealistic and dumb for those who do proper detectives work doing sting operations etc.

**Comment by ladojrp-sourdirt** [comment]
Hello Bright this is Sourdirt with the LADOJRP Suggestions team

Thank you for this suggestion and this will be read very carefully and taken under consideration.

I understand your idea of adding Black Market access back to LEO but I can't make any promises. I will pass this up to see if SA+ think this is a good idea/suggestion. 

They will decide and make a vote on it and thank you again for reaching out to the suggestion team. These don't go unnoticed.

Administrator, Sourdirt

**Comment by ladojrp-sourdirt** [comment]
@ladojrp-alopez ^

**Comment by ladojrp-alopez** [comment]
Hello Bright this is Lopez with the LADOJRP Suggestions team,

I have read your suggestion, and originally the black market for law enforcement was not able to see, and I think it should stay that way. There should be a bottom line, 50/50 advantage for civilians to sell illegal drugs without having every detective on every scene. It is best to keep it minimum. To my knowledge, it makes it fun, and more exciting knowing if that location will have a drug deal or not. Also, I believe you guys can also go undercover so you also have an advantage knowing if the civilians knows or not. Overall, your suggestion will be denied for the meantime if any executive member object, they can pass it up. 

LADOJRP Suggestions Team
