### ISSUE TITLE
200 MPH Speed Limiter?

### ISSUE THREAD

**Issue by CharlieHunter1** [ScottUK/ladojrp-issues#107]
**Describe the feature you'd like implemented**
Update the Speed Cap to 200 MPH.

**Comment by ladojrp-bell** [comment]
nah

**Comment by ladojrp-sourdirt** [comment]
Hello C. Hunter this is Sourdirt with the LADOJRP Suggestions team

Thank you for this suggestion.

I understand your idea of increasing the speed cap on the server to 200 MPH but I don't believe this personally would be a good idea. Realistically almost all vehicles manufactured in the U.S are govern'd at 130ish depending on the vehicle and would be a form of unrealism. I also noticed when the speed cap was temporarily disabled people signifcantly abused it to the extent that it caused many unnecessary accidents and for 10-80's to get 22'd more than I could. I appreciate your suggestion but unfortunately we will have to deny this. 

Thank you again for reaching out to the suggestion team and if you think of any other bugs and/or ideas please feel free to open up a new suggestion/issue.

Administrator, Sourdirt
