### ISSUE TITLE
Menu after a kick

### ISSUE THREAD

**Issue by KongeHvH** [ScottUK/ladojrp-issues#108]
I don't know if this is even possible but I think it's a good recommendation. If you're kicked from the game and you rejoin after a kick it puts you in a room and makes you wait 5 minutes and read the rules in the f5 menu or something along the lines of that. It does sound a little stupid but then the kick actually makes them have a quick timeout.

**Comment by ladojrp-sourdirt** [comment]
Hello Konge this is Sourdirt with the LADOJRP Suggestions team

Thank you for this suggestion and this will be read very carefully and taken under consideration.

I understand your idea of adding a script where if you get kicked/banned and I will pass this up to see what the higher ups have their opinioin on this. I personally believe this is a great suggestion and should be added.

They will decide and make a vote on it and thank you again for reaching out to the suggestion team. These don't go unnoticed.

Administrator, Sourdirt

**Comment by LADOJRP-Mello** [comment]
Thank you for your suggestion, We will not be looking into adding this in the near future.
