### ISSUE TITLE
Break out of Cuffs script?

### ISSUE THREAD

**Issue by itsCrummy** [ScottUK/ladojrp-issues#11]
**Describe the feature you'd like implemented**
Basically when your being cuffed - you should have a chance to break out of the Cuffs - Like a Sort of... Minigame type thing... where ithe suspect can resist arrest and actually break out of the cops restraints whilst being cuffed.

**Link to the resource if it already exists**
IDK

**Additional context**
idk

**Comment by XXCurse54XX** [comment]
some qbus scripts and esx scripts have lockpicking minigames, i dont know about lado tho, it could be a purchasable item for the inventory.

**Comment by ScottUK** [comment]
There won't be a needed item, it will just be a really hard minigame that happens.

**Comment by ladojrp-alopez** [comment]
Hello, I am Lopez, in charge of overseeing suggestions team, your suggestion has been denied by our head of development team. 

-LADOJRP Suggestions Team
