### ISSUE TITLE
New weapon

### ISSUE THREAD

**Issue by D-Kreiger** [ScottUK/ladojrp-issues#111]
**Describe the feature you'd like implemented**
A clear and concise description of what you want implemented into the server.
Id like a new weapon added. we currently have no good and realistic shotguns besides the sawed off (atleast in my opinion)
**Link to the resource if it already exists**
If it already exists, post the link to the resource here.
https://www.gta5-mods.com/weapons/remington-870
**Additional context**
i think this would be good for leo and civs.

**Comment by Shanvir13** [comment]
Thats a cool weapon I agree it should be added

**Comment by ladojrp-bell** [comment]
not at this time

**Comment by ladojrp-sourdirt** [comment]
Hello Kreiger this is Sourdirt with the LADOJRP Suggestions team

Thank you for this suggestion and this will be read very carefully and taken under consideration.

I understand your idea of adding a shotgun as an extra weapon into the server. I personally don't see an issue with it but we currently have a large amount of things we are currently working on. If maybe at a later time we will take this under consideration. 

Thank you again for your suggestion.

Administrator, Sourdirt
