### ISSUE TITLE
adding low traffic AI

### ISSUE THREAD

**Issue by D-Kreiger** [ScottUK/ladojrp-issues#113]
**Describe the feature you'd like implemented**
A clear and concise description of what you want implemented into the server.
 i would like to add low level amounts of traffic, not too much that when you walk in the road you get slapped by AI every half a second but enough that when the server has less people it doesnt feel like a ghost town or apocolypse
**Link to the resource if it already exists**
If it already exists, post the link to the resource here.
i assume traffic multiplier is just at 0.0?
**Additional context**
n/a

**Comment by ladojrp-sourdirt** [comment]
Hello Kreiger this is Sourdirt with the LADOJRP Suggestions team

Thank you for this suggestion and this will be read very carefully and taken under consideration.

I understand your idea of adding AI traffic back into the server. I personally don't see an issue with it but we currently have a large amount of things we are currently working on. If maybe at a later time we will take this under consideration. Also there has been issues with the AI deciding to cause VDM, RDM, and interfering with LEO scenes.

Thank you again for your suggestion.

Administrator, Sourdirt
