### ISSUE TITLE
vehicle tracker

### ISSUE THREAD

**Issue by xdDevion** [ScottUK/ladojrp-issues#118]
**Describe the feature you'd like implemented**
A clear and concise description of what you want implemented into the server.
i think it would be fun to have a script that allows you to add a tracker to a personal vehicle followed by a way to hack off and steal a vehicle with a tracker it will make stealing cars less worthless kind of like no pixel car boosting but with its own little spin on it
**Li  nk to the resource if it already exists**
If it already exists, post the link to the resource here.
not that i know of
**Additional context**
N\A

**Comment by LADOJRP-Mello** [comment]
Thanks for your suggestion, 

Your first idea of "add a tracker to a personal vehicle" is already in game! Press "F1" then set your car as personal vehicle, and scroll down and you shall see a option to have a tracker!

We will not be looking into "hack off and steal a vehicle with a tracker" in the near future, Thank you for your suggestion!
