### ISSUE TITLE
Equal pay with LAFD and LEO

### ISSUE THREAD

**Issue by Green5tar1** [ScottUK/ladojrp-issues#12]
Right now LEO get 2000 paycheck and LAFD 1700. Can we get it so LAFD also get 2000? Only fair.

**Comment by ladojrp-alopez** [comment]
Hello Greenstar, I am Lopez, in charge of the Suggestions Team, I am here contacting and giving out some handful information,

Please discuss this and refer your suggestions to our Top 5 Chat we have in the main discord and contact one of our Assistant Directors for your request per the department

-LADOJRP Suggestions Team

**Comment by ScottUK** [comment]
This has been added.
