### ISSUE TITLE
Stuck chat

### ISSUE THREAD

**Issue by Jord-0** [ScottUK/ladojrp-issues#125]
Chat keeps getting stuck meaning i cant move around. 

Have to leave and join back to fix it. 
It stops me from walking and typing.

**Comment by LADOJRP-Mello** [comment]
If you have any clips or some type of way to show us this incident please send it here, We haven't noticed this issue!

**Comment by ConnorLADOJRP** [comment]
If this issue happens again please make a discord ticket as no one else has had this issue
