### ISSUE TITLE
TS Roles

### ISSUE THREAD

**Issue by Brightttttt** [ScottUK/ladojrp-issues#126]
Make a cal fire role in the team-speak as that is now an LAFD sub division.

**Comment by Ferrana** [comment]
yes pls as The head of it that Would be AMAZING!!!!

**Comment by LADOJRP-Mello** [comment]
Your suggestion has been passed up and is being looked into. Expect updates to be posted here.

**Comment by LADOJRP-Mello** [comment]
Your suggestion has been completed, You should be able to find "Cal Fire" role in teamspeak now. Any issues with the role please open a ticket!
