### ISSUE TITLE
Penal code addition request

### ISSUE THREAD

**Issue by GrimJH** [ScottUK/ladojrp-issues#131]
**Describe the feature you'd like implemented**
I and a few members of the LAPD would like "Criminal Negligence" to be added to the penal code seeing as we don't have a charge of this nature and as we continue to make arrests, each situation evolves and recent issues have been evolving into subjects we cannot charge individuals on or it's not stated in the penal code leading to confusion, Criminal Negligence is described as; "Definitions of criminal negligence. (law) recklessly acting without reasonable caution and putting another person at risk of injury or death (or failing to do something with the same consequences)" 

**Link to the resource if it already exists**
(https://www.shouselaw.com/ca/defense/laws/criminal-negligence/#:~:text=California%20criminal%20law%20uses%20the,indifference%20to%20human%20life%2C%20and)

**Additional context**
N/A

**Comment by LadojrpAustin** [comment]
Hello GrimJH, I am Austin with the LADOJRP Suggestions team

Before I continue I would like to thank you for making this suggestion

This would be a good idea so I'll pass this up to Head of Suggestions

 @ConnorLADOJRP 
 
 Administrator, Austin

**Comment by GrimJH** [comment]
No problem man just looking to improve RP and fill in the grey-areas we have as a police department

**Comment by LADOJRP-Mello** [comment]
Hello @GrimJH I have looked at your request and successfully brought it a community managers' attention, Thanks for your suggestions and you will be updated on their decision!

**Comment by LADOJRP-Mello** [comment]
Hello @GrimJH , "Criminal Negligence" is now in the penal codes section, Thanks for your suggestion!
