### ISSUE TITLE
Music bug

### ISSUE THREAD

**Issue by Wascablewe** [ScottUK/ladojrp-issues#135]
While in a car, the music player is broke, mine will not go over %25 volume, and it is just straight up bugged with the script to play and pause, it is way delayed

**Comment by itsCrummy** [comment]
the music player is not meant to go above 25% it is scripted that way so it doesnt go above that number

**Comment by ladojrp-sourdirt** [comment]
Hello Keegan this is Sourdirt with the LADOJRP Suggestions team

Thank you for this bug report and this will be read very carefully and taken under consideration.

So what Crummy had commented the car player volume is limited to 25% and it is also a server rule as there has been numerous cases of people blasting music and it can be perceived as cop-baiting, trolling, or even NITRP. I understand there might be a delay between pausing and playing the music but unfortunately there isn't much that can be done to fix that as it's complicated to explain but the script itself can't be modified to the extent there is less delay between the response of the buttons itself.

We appreciate you reporting this but unfortunately it won't be altered so the volume will go above 25%.

Administrator, Sourdirt
