### ISSUE TITLE
Penal code sheet.

### ISSUE THREAD

**Issue by Brightttttt** [ScottUK/ladojrp-issues#16]
Add more penal codes to the penal code sheet.

**Comment by ladojrp-alopez** [comment]
Hello Bright, I am Lopez, in charge of the Suggestions Team, I am here contacting and giving out some handful information,

Please have your department heads discuss with the Bell, our Assistant Director who oversees the Law Enforcement. They can reach out to him in our chat we have!

-LADOJRP Suggestions Team
