### ISSUE TITLE
Move /respawn sandy to Nowhere Rd - 1037

### ISSUE THREAD

**Issue by WiredOrange** [ScottUK/ladojrp-issues#18]
**Describe the feature you'd like implemented**
We are a Department of Justice server. Which means we are generally surrounded and somehow involved with the police. The police station is a very important spot for the police as it is literally where we get cars, arrest people, have our own RP, get changed, etc etc... Understandably and happily, the police station is a green zone. Although that is great, it also allows people to spawn cars. Allowing people to spawn cars, and "get into character" leads to people messing around such as jumping and running around for no reason, riding their bikes all around, spawning in 15 different cars, leaving cars all over, and just doing stupid RP. 

Having people spawn there means that everyone who comes into sandy has to come to the PD. This causes a lot of issues for the police because then people mess with the RP which breaks immersion. Yes I can call a staff member but the fact that this happens a lot it needs to be addressed. I feel as if we moved the spawn point from the PD to Nowhere Rd, it would move people away from the police station and it wouldn't disrupt the RP that is happening there.

**Comment by ladojrp-alopez** [comment]
Hello WiredOrange, I am Lopez, in charge of the Suggestions Team, I am here contacting and giving out some handful information regarding your suggestion,

I totally agree with how much the role play at Sandy PD can get, as a staff member, this is a issue we get reports from. I understand your view and how much it ruins the role play, but regarding putting it at the spawn location to Nowhere RD. would not change anything as it is right in the middle of Sandy-Flywheels. The location you requested will do no good, perhaps you have a different location in mind? (Note: This is not a guaranteed acceptance)

- LADOJRP Suggestions Team
