### ISSUE TITLE
Rule Update

### ISSUE THREAD

**Issue by 2E-85-RugerD** [ScottUK/ladojrp-issues#20]
I believe that a tab about shooting on hold/prio should be added going into depth upon the rules that go along with it, as many people get warnings for not knowing about those rules!

**Comment by Brightttttt** [comment]
So it is clearly explained in the rules that you cannot shoot at all while prio is on hold. Would you like to elaborate and tell me about something that could be added to the rule?

**Comment by 2E-85-RugerD** [comment]
> 

I was thinking in the quick access rule view F5 menu, we should add a tab about weapon usage within different prio settings

**Comment by ScottUK** [comment]
Denied as it goes into detail in the rules already. :p

This is a rule in a lot of servers.
