### ISSUE TITLE
LAPD Drill Instructor Hat

### ISSUE THREAD

**Issue by Brightttttt** [ScottUK/ladojrp-issues#21]
https://no.gta5-mods.com/player/lspd-drill-instructor-campaign-hat-eup-replace-fivem-ready

This is would be for trainings. This is the hat they wear IRL and it would be really cool to have,

**Comment by ladojrp-alopez** [comment]
This would only benefit LAPD and not other departments. Unforn. this will be denied. Unless you can find one for all departments by all means, send the link.

**Comment by Brightttttt** [comment]
All the other departments have a hat like that

**Comment by Brightttttt** [comment]
LASD and CHP has 1 and I am pretty sure they even have multiple so letting LAPD have one would just be fair.

**Comment by ladojrp-alopez** [comment]
Have your LAPD department administration take a look at it, if they agree, they can speak to the proper Executive Staff member and request it.

**Comment by Brightttttt** [comment]
Will do
