### ISSUE TITLE
Add Dirt Bike.

### ISSUE THREAD

**Issue by pinkey69** [ScottUK/ladojrp-issues#24]
add bikes to Silver, Gold, or Diamond. Or make another Project...  Project: Bikes?

**Comment by ScottUK** [comment]
I've added a dirt bike for you for now, spawn code: DirtBike (Anyone can use it)

I'll start work on a project bikes, but please keep in mind it might take a while. :)

**Comment by ScottUK** [comment]
This is done, but I've made #50 for Project Bikes. :)
