### ISSUE TITLE
Rule Update - LEO Checking Cameras

### ISSUE THREAD

**Issue by CharlieHunter1** [ScottUK/ladojrp-issues#28]
I believe there needs to be a cooldown, or some sort of rule, added around LEO checking cameras. They check cameras every other minute during priorities, and it just doesn't make it very fun.

**Comment by Green5tar1** [comment]
I agree, maybe like every 5/10 minutes the cooldown should be

**Comment by LadojrpAustin** [comment]
Hello this is Austin with the suggestions team

This Suggestion would technically be a Department suggestion due to the fact that it's related to a department and would most likely be added as a Policy.

Have a good day
- Administrator, Austin
