### ISSUE TITLE
Loading screen music

### ISSUE THREAD

**Issue by Rubenv24** [ScottUK/ladojrp-issues#29]
change the Loading screen music to gucci flip flops, https://youtu.be/ZmXWpISlJ_E heres the link

**Comment by ScottUK** [comment]
We can't use copyrighted music, but we'll look into changing the music. :)

**Comment by Rubenv24** [comment]
Make your own song ;)

**Comment by ladojrp-alopez** [comment]
Hello, this is Lopez, overseeing the suggestions that get placed for the community of Los Angeles Department of Justice Roleplay,

Loading screen music has been changed! Thanks for the suggestion.

-LADOJRP Suggestions Team
