### ISSUE TITLE
LAFD Sandy Shores Fire station

### ISSUE THREAD

**Issue by Brightttttt** [ScottUK/ladojrp-issues#3]
I am here to suggest that LAFD gets a station in sandy. We can barely fit when we have a lot of people on in that station and it is very crammed and not very enjoyable. We have a bunch of new interiors and I think that giving LAFD a sandy fire station would improve rp a lot. Even just an interior of the fire station would also be nice! https://www.youtube.com/watch?v=ntBx5aGgT_k Like this.

**Comment by Jord-0** [comment]
We had one but it caused major lag. They will work on one eventually but it's not need right now.

**Comment by ScottUK** [comment]
Lord Jord said, most of them cause lag including this one. I don't actually think there is one out there that doesn't cause lag. It's not an issue that we don't want to add one, it's that we can't find one. :)

**Comment by Brightttttt** [comment]
Bruh.













































BRuh.

ons. 15. des. 2021 kl. 17:49 skrev ScottUK ***@***.***>:

**Comment by ladojrp-alopez** [comment]
Hello Bright, I am Lopez, in charge of the Suggestions Team, I am here contacting and giving out some handful information,

Bell has been working on finding new a station. He was planning to add one soon! Thanks for the suggestion!

- LADOJRP Suggestions Team
