### ISSUE TITLE
Broken HUD - Constantly Flashing

### ISSUE THREAD

**Issue by CharlieHunter1** [ScottUK/ladojrp-issues#31]
**Description of the problem**
The HUD next to the map tends to randomly start constantly flashing.

**Reproduction steps**
Unsure of the cause, so can't tell how to produce.

**Expected behavior**
For the HUD not to be constantly flashing, and rather to stay still

**Screenshots**
YT VIDEO - https://youtu.be/75I-SUlkg_4

**Comment by ScottUK** [comment]
A fix has been added for the next restart, this was an issue for people with high FPS. It was introduced during a previous developers update. Not sure how they managed to mess something really simple up but it's all good now!

**Comment by ScottUK** [comment]
Side note: Good issue, great video. Thanks for that.
