### ISSUE TITLE
FBI

### ISSUE THREAD

**Issue by Brightttttt** [ScottUK/ladojrp-issues#34]
Bring back FBI I think the state of the server RP is good enough for FBI to RP and it would be really cool to have back as a RP asset on the server.

**Comment by WiredOrange** [comment]
"the server RP is good enough"
Ha... haha... funny joke.. lmao I never thought of putting a joke on here.

The RP fucking sucks on the server. Spend 10 minutes as LEO.

**Comment by ScottUK** [comment]
We'd bring it back if it had good RP in the first place, it was either FailRP or just raids 24/7 based on no previous roleplay.

I'm afraid we won't consider adding FBI back. :(

**Comment by Brightttttt** [comment]
> "the server RP is good enough" Ha... haha... funny joke.. lmao I never thought of putting a joke on here.
> 
> The RP fucking sucks on the server. Spend 10 minutes as LEO.

And you play on this server lol. if the rp sucks so much why even be LEO on this server. Instead of complaining make a change bud.

**Comment by Brightttttt** [comment]
If you actually partake in good rp not making it shit you will actually have fun lmao.
