### ISSUE TITLE
LACD Rank Permissions TS (Issues)

### ISSUE THREAD

**Issue by Alvarez1033** [ScottUK/ladojrp-issues#35]
**Describe the feature you'd like implemented**
The ability to move ranks based on dispatch rank.

**Link to the resource if it already exists**
N/A

**Additional context**
As dispatchers, we often have to move units out of channels to contact other units or during various situations. For example, many times there are tactical situations that are occurring. Instead of units being able to request dispatch to switch the units on the scene over to a tac channel, they have to tab out of the game and potentially the risking situation failing. During this situation, it is important for dispatch to be able to switch the units over without them having to tab out. Another situation where this would be helpful is when a supervisor needs to speak to a unit, or a unit is AFK in the channel. 
Currently, any dispatch rank below Assistant Direct (I believe) is not able to move any unit no matter rank. This is an issue as dispatchers are tasked with organizing the channels.

**Currently, ranks are not able to move any other rank, thus reducing the efficiency of dispatch and RTO mitigation**
I am suggesting to allow the following:
1) All dispatch ranks being able to move all LEO/Fire/DOJ/TMOD and below, that is not above TMOD.
2) Dispatcher being able to move all ranks stated above including TMOD.
3) Senior Dispatcher (Dispatch II) being able to move Moderators and below.
3) Supervisory Dispatcher being able to move Senior Moderators/Developers and below.
4) Assistant Manager being able to move Administrator and below.
5) Manager being able to move Administrator and below.
6) Assistant Director being able to move Senior Administrator and below.
7) Deputy Director being able to move Senior or Head administrator and below.
8) Director being able to move Head Administrator or any higher rank. 

The list stated above is the staff ranks that would apply. It should be stated that the ranks above should be able to also move any Non-Staff rank to aid in organization and reduce chaos in RTO. The different ranks should be able to move a higher rank as the dispatcher climbs the ranks and becomes more trustworthy within the department. We will hold this policy to the highest standards and any mistakes will be met with consequences possibly leading to termination if abused.

Thank you,
Alvarez
LACD Director
Alvarez#2161

**Comment by ladojrp-bell** [comment]
I will do some of these permissions, but I will not give the ability to move any of the admin team.

**Comment by ScottUK** [comment]
Added. :)
