### ISSUE TITLE
LACD Rank Permissions | Part 2

### ISSUE THREAD

**Issue by Alvarez1033** [ScottUK/ladojrp-issues#36]
**Describe the feature you'd like implemented**
The ability for ranks to assign ranks to dispatchers once reached Supervisor+

**Link to the resource if it already exists**
N/A

**Additional context**
The ability for the following to be changed/fixed on TS:
1) Supervisory Dispatcher able to assign **all ranks below their rank.**
2) Assistant Manager able to assign any ranks below Supervisor **(Same as supervisor- Below Supervisor)**
3) Manager able to assign any ranks below Assistant Manager **(Able to assign supervisor rank)**
4) Assistant Director being able to assign any ranks below Manager **(Able to assign Assistant Manager)** 
5) Deputy Director being able to assign any ranks below Assistant Director **(Able to assign Manager)**
6) Director being able to **assign any ranks, including director (If able) in the LACD department.**

This will allow for max efficiency within the department as it doesn't require the highest to be on to assign ranks. The ability to assign these ranks will be monitored and will be held to a high standard. If broken, met with consequences or termination. 

Thank you,
Alvarez
LACD Director
Alvarez#2161

**Comment by ladojrp-bell** [comment]
As stated before, I will do these as well.

**Comment by ScottUK** [comment]
Added. :)
