### ISSUE TITLE
9-1-1 Call Overlay Removal - Losing control of ELS and driving capabilities for Controller Players.

### ISSUE THREAD

**Issue by Novanance** [ScottUK/ladojrp-issues#43]
The old cad systems 9-1-1 call overlay still comes up and is a hassle for LEO who use controllers and attempt to change siren tones (You cannot steer with it open).

**Reproduction steps**
Not too sure as to the keyboard button, but on an XBOX Controller the Bottom D-Pad opens it up. The little bar where calls would pop up will show and a cursor will appear, causing the vehicle to be uncontrollable.

**Expected behavior**
Should not be ingame still as it is not connected to the CAD.

**Screenshots**
![image](https://user-images.githubusercontent.com/29945584/147891127-edcef097-f5fc-4968-bcc5-da02f112f6af.png)
![image](https://user-images.githubusercontent.com/29945584/147891155-7ec5424f-0e3a-4b1d-8132-d0bb1df7b4ea.png)

**Comment by ScottUK** [comment]
I'll have a look at getting that fixed within the next few hours.

**Comment by ScottUK** [comment]
Removed for next restart. :)

**Comment by liamoc5402** [comment]
its not fixed it still happens but also messes with breaking so u just start accelerating forward with no turning
