### ISSUE TITLE
Bug Report: Command's Bug (2)

### ISSUE THREAD

**Issue by CharlieHunter1** [ScottUK/ladojrp-issues#48]
**Description of the problem**
A number of commands are currently broken:
- /carry
- /drag
- /th and /takehostage
- Emote Script
- Ragdoll Script (U)

**Reproduction steps**
Use the commands on people to reproduce

**Expected behavior**
For the commands to work properly i.e Carry, Drag, Takehostage, Carry out the Emotes, Ragdoll

**Screenshots**
N/A

**Additional information**
YouTube Video - https://youtu.be/U-fdAlr9x6g

**Comment by ScottUK** [comment]
Duplicate of #45 , but I'll close that one since this is formatted better. :)

**Comment by ScottUK** [comment]
Looks like this is an issue with the latest GTA update and attaching people together. I might have to overhaul these commands. 🤔

**Comment by ScottUK** [comment]
Ragdoll cannot be fixed, but everything else should be good. :)
