### ISSUE TITLE
New Update 

### ISSUE THREAD

**Issue by AquaticOtter12** [ScottUK/ladojrp-issues#5]
If there is any chance if the server can get the new GTA 5 Online Update.

**Comment by ScottUK** [comment]
Which one specifically, was there a new DLC?

**Comment by AquaticOtter12** [comment]
> Which one specifically, was there a new DLC?
Yea they came out with a new dlc it’s got new cars and stuff

**Comment by ScottUK** [comment]
The tuners DLC?

**Comment by AquaticOtter12** [comment]
> The tuners DLC?

Its the brand new one and its called "The Contract".

**Comment by ScottUK** [comment]
I'll have a meeting with the executive team next Saturday to see if we should update.

**Comment by AquaticOtter12** [comment]
> I'll have a meeting with the executive team next Saturday to see if we should update.

Alright thank you!

**Comment by ScottUK** [comment]
FiveM doesn't support that DLC right now. But we'll consider updating when it comes around to them supporting it.

**Comment by ScottUK** [comment]
Server was updated to latest DLC to fix crashes, if all is well it will be kept. Otherwise it will be reverted.
