### ISSUE TITLE
Vstancer.

### ISSUE THREAD

**Issue by Rubenv42** [ScottUK/ladojrp-issues#54]
Bring back the Vehicle stancer, it was so cool and make and gave us some more fun things to do with our vehicles,.

**Comment by LadojrpAustin** [comment]
Hello Ruben, This is Austin with the LADOJRP Suggestion Team

I have noticed you made a suggestion about the VStancer menu

We had this menu open a while ago at least more then 6 months ago when we had this public it was abused and was used very unrealistically sadly this was denied in the past and will most likely not be approved.

Administrator, Austin

**Comment by ScottUK** [comment]
Just to add on to Austin's response, it causes too much lag. :)
