### ISSUE TITLE
DEA/DOA

### ISSUE THREAD

**Issue by Brightttttt** [ScottUK/ladojrp-issues#58]
So when departmenonts cool a little down and starts to run smoothly I suggest execs make a DEA department. Kinda like fbi but it’s something else and there are tons of drug rp in the server so I think this would be something really cool and useful to have.

**Comment by Brightttttt** [comment]
This would be a really cool department to have and improve the overall drug rp which I mean the drug rp on the server is actually quite good.

**Comment by ladojrp-bell** [comment]
We will not be looking into this further.

**Comment by ladojrp-alopez** [comment]
What bell said
