### ISSUE TITLE
New Billboard at Sandy (east joshua!)

### ISSUE THREAD

**Issue by ladojrp-alopez** [ScottUK/ladojrp-issues#6]
(SUGGESTION) For someone who has been playing Five M for a while, I think it would be a cool idea to add a new template in the Billboard at East Joshua. It will add some spice/touch to the server! There is lots of examples that can be used

**Comment by ScottUK** [comment]
I'll ask the media team if it's something they want to do.

**Comment by LADOJRP-Mello** [comment]
The Community management has declined this suggestion, although this is a good suggestion we are not currently looking into it.
