### ISSUE TITLE
By removing the 911 tab for controller it only made it worse (police vehicles on controller)

### ISSUE THREAD

**Issue by liamoc5402** [ScottUK/ladojrp-issues#60]
**Description of the problem**
If you have your lights on and no sirens if you are accelerating and hit down on dpad to turn lights on you start accelerating cannot break and cannot steer so you turn into a torpedo that usually end up crashing for hitting someone. its happened me ever since the 911 tab was removed. 

**Reproduction steps**
turn on lights on a 2018 charger (only one ive use not sure if its just this car ) and start accelerating and hit down on d pad 

**Expected behavior**
meant to just turn sirens on 

**Screenshots**
none

**Comment by liamoc5402** [comment]
just to add on i think i know what the issue is its the emote keybind for Z its causes you to loose all control

**Comment by ScottUK** [comment]
I'll fix this tonight. :)

**Comment by LADOJRP-Mello** [comment]
Has your issue been resolved?

**Comment by ConnorLADOJRP** [comment]
This issue has been resolved thanks for your suggestion -Connor
