### ISSUE TITLE
Donator F4 Menu bug/issue 

### ISSUE THREAD

**Issue by ladojrp-sourdirt** [ScottUK/ladojrp-issues#68]
**Description of the problem**
I was scrolling through the F4 dono vehicles and after spawning a few in the gold section my menu froze and even with backspace, F4, Esc, I can't seem to get anything to close the menu visually however it acts as it its not open and Enter doesn't do anything its just visually stuck.

**Reproduction steps**
All I did was scroll through the gold and spawn a few vehicles then after pressing backspace it just didn't disappear visually however I can still use the menu blindly and makes sounds if I had the menu memorized.

**Expected behavior**
Well to be honestly I know its brand new so I figured there'd be bugs but yeah just hoping we can get this fixed so the menu isn't frozen visually so we don't have to relog to fix temporarily.

**Screenshots**
(https://cdn.discordapp.com/attachments/686840204367101957/929749502229889044/unknown.png)

**Additional information**

**Comment by ScottUK** [comment]
Thanks for the report, looks like an issue with the menu framework I'm using. I'll see about fixing this. :)
