### ISSUE TITLE
Bring Back Sonoran Cad

### ISSUE THREAD

**Issue by LiamBowker** [ScottUK/ladojrp-issues#71]
**Describe the feature you'd like implemented**
A clear and concise description of what you want implemented into the server.

I think that Sonoran cad should be brought back as the cad we have now is not the best and myself a few others miss the old cad and I’m sure a lot more others do too.

**Link to the resource if it already exists**
If it already exists, post the link to the resource here.

**Additional context**

**Comment by liamoc5402** [comment]
new cad works fine its alot easier to see peoples info while onduty and its alot less glitchy.

**Comment by ladojrp-alopez** [comment]
Hello, I am Lopez, in charge of suggestions team, 

The change of switching cad has been denied. This cad brings more a friendly tool for managing departments, and other things that are self explanatory. Hamz cad also makes it easier as it used discord roles for duty access rather the sonoran cad you would have to search the username

-LADOJRP Suggestions Team
