### ISSUE TITLE
PA System For Police

### ISSUE THREAD

**Issue by LiamBowker** [ScottUK/ladojrp-issues#73]
**Describe the feature you'd like implemented**

There should be a PA system for police to use in their vehicles so if they need to yell for a vehicle to pull over or pull closer to the side of the road they can do so by using that implemented PA system.

**Comment by ladojrp-alopez** [comment]
Hello, I am Lopez in charge of overseeing suggestions, 

You can download a voice mod for a PA system voice, download a simple voice changer that allows key binds for you to access it. If you need help, contact me via Discord x (Lopez#2022)

-LADOJRP Suggestions Team

**Comment by LiamBowker** [comment]
> Hello, I am Lopez in charge of overseeing suggestions,
> 
> You can download a voice mod for a PA system voice, download a simple voice changer that allows key binds for you to access it. If you need help, contact me via Discord x (Lopez#2022)
> 
> -LADOJRP Suggestions Team

Yes I know that but you have to purchase the voice mod premium to gain access to the PA system voice. Not everyone can afford to pay for it
