### ISSUE TITLE
Motorcycles.

### ISSUE THREAD

**Issue by Rubenv42** [ScottUK/ladojrp-issues#75]
Add some more motorbikes, like dirt bikes or cruisers, or regular street bikes... And maybe give it to donators instead of making it one huge pack...

**Comment by Brightttttt** [comment]
+1 Add more then just race bikes. Add more old ones maybe even add a moped😎

**Comment by Rubenv42** [comment]
ye thats what i mean not just race bikes

**Comment by ladojrp-bell** [comment]
Hello and Thank you for reaching out to the LADOJRP Suggestions Team!

If you are able to find links to bikes that would be suitable for the server's tedious requirements (under 300k polys, not bulletproof in any manner, realistic), you are more than welcome to open a ticket in the main discord and suggest we put it in one of the donator packs. At this time, I am unsure of your donator rank, and we cannot guarantee that the bikes, if put in, will match your donation tier, but we do always try to ensure max community positivity.

With that said, this is resolved.

Thank you again for reaching out, have a good night!
Bell - Assistant Director

**Comment by ladojrp-alopez** [comment]
test
