### ISSUE TITLE
Remove Crosshair 

### ISSUE THREAD

**Issue by ladojrp-alopez** [ScottUK/ladojrp-issues#76]
**Describe the feature you'd like implemented**
A clear and concise description of what you want implemented into the server.

Remove the crosshair 

**Link to the resource if it already exists**
If it already exists, post the link to the resource here.

No link

**Additional context**

Removing the crosshair will allow more realism and more difficulty while killing someone whether for law enforcement, or for civilians. More deaths happen quicker which ruin the purpose of the realism we hope. The crosshairs just gives the feeling of we are playing a random GTAV online session, as having the small details such as removing the crosshairs gives the feeling, yet the idea of holy shit, this is hard to kill someone let’s hope my accuracy is on point.

**Comment by ladojrp-bell** [comment]
A community vote was put to see what everyone wanted, they wanted it back. The answer is no for now.
