### ISSUE TITLE
CHP Plane

### ISSUE THREAD

**Issue by Brightttttt** [ScottUK/ladojrp-issues#77]
https://forum.cfx.re/t/release-highway-patrol-c172-airplane-chp-based/1028607

**Comment by ladojrp-alopez** [comment]
Hello, this is Lopez, in charge of overseeing suggestions that get suggested through LADOJRP,

I am looking at your suggestion and it has come to conclusion this is not needed. If any community director would like to add this, they can, however this is not Top 5 for CHP/LEO priority. Thanks for your suggestion. 

-LADOJRP Suggestion

**Comment by ladojrp-alopez** [comment]
Hello, I am Lopez, in charge of responding and overseeing the suggestions that come through within the LADOJRP Community, 

It has brought to my attention, your suggestion will denied 

Reasons for Denial:

- Not needed

- Low priority for the department of Law Enforcement

- ETC


-LADOJRP Suggestions Team.

**Comment by Novanance** [comment]
Myself & Singh also tried implementing this a very long time ago, however, it turned out pretty crappy ingame and didn't work right so therefore it was not added.
