### ISSUE TITLE
A new dealership. 

### ISSUE THREAD

**Issue by KongeHvH** [ScottUK/ladojrp-issues#79]
I think it would be cool to add a dealership at the sisyphus theater. Like this one
https://www.gta5-mods.com/maps/car-dealership-showroom-fivem-y-map-ymap
I don't know if you guys are currently taking building suggestions just figured this is something that is cool and seems like it could be a cool place to add and as well sell vehicles.

**Comment by ladojrp-sourdirt** [comment]
Thank you for your suggestion but I don't believe we are accepting / adding other interiors and/or YMAP buildings at the moment. I can bump this to a higher up and see about their input if you would like.
