### ISSUE TITLE
Adding a new car to donator packs of the free month vehicle pack 

### ISSUE THREAD

**Issue by DGoodw1n** [ScottUK/ladojrp-issues#8]
Hey Scotty, I am wondering if we can get the Alpha Romeo Gulia, and a 2020 Toyota camary in game. Whether it be a free month car or a donator car. Something new and different that we haven’t had yet.

**Comment by ScottUK** [comment]
Can you be specify links to the vehicles you wanted adding please?

**Comment by LADOJRP-Mello** [comment]
19 Days inactivity in ticket, Thank you for your interest. Please provide us with links in the future and make a new suggestion.
