### ISSUE TITLE
Security Rules

### ISSUE THREAD

**Issue by VyrixAlpha** [ScottUK/ladojrp-issues#81]
**Describe the feature you'd like implemented**
Remove the rule of security not being able to open carry as long as we wear clothing that is a clear sign of security like a badge or the wording.

**Additional context**

![Cal open carry law](https://user-images.githubusercontent.com/97772144/149605579-51de8532-2abc-4f28-89da-a7ec59c6652a.png)

**Comment by LADOJRP-Mello** [comment]
Thank you for your suggestion, This idea is being voted upon currently, and we will follow up with an answer soon! 

Thanks,
LADOJRP Executive Staff

**Comment by LADOJRP-Mello** [comment]
After a vote, your suggestion has been considered but unfortunately, we will not be looking into changing this. Thanks for your suggestions!
