### ISSUE TITLE
CRUISE CONTROL!!!

### ISSUE THREAD

**Issue by Brightttttt** [ScottUK/ladojrp-issues#82]
Please add cruise control back it is annoying to always tap when you need to follow the speed limit.

**Comment by ladojrp-sourdirt** [comment]
Hello we appreciate the suggestion but this was already mentioned and Scotty is looking into it. Here is the direct link to it so you don't get them mixed up. Thank you again for the suggestion as these don't go unnoticed. Have a great day/night. 
https://github.com/ScottUK/ladojrp-issues/issues/37
Sincerely,
-Sourdirt (LADOJRP)
