### ISSUE TITLE
LAFD Plane

### ISSUE THREAD

**Issue by Brightttttt** [ScottUK/ladojrp-issues#83]
So as we are getting a new LAFD pack why add a plane to RP with https://aerocorner.com/aircraft/bombardier-415/ . It would be really cool to have in the AO sub division and I think that adding it onto the pack would be amazing!

**Comment by Brightttttt** [comment]
Jk here is the right link https://no.gta5-mods.com/vehicles/canadair-cl-415-add-on-working-water

**Comment by ladojrp-sourdirt** [comment]
I personally don't see a reason to add a plane there is already a helicopter for LAFD.

**Comment by LadojrpAustin** [comment]
Hello Bright I am Austin with the LADOJRP Suggestions team.

Thank you for this suggestion and this will be looked at very carefully

Bright you have to take into consideration this will be useless it's not like you can land on the dirt road ETC and you guys already have a helicopter so there will be no reason to add this Airplane into the LAFD Vehicle pack.

**Comment by Brightttttt** [comment]
Idk if you know how a wild fire plane works Austin but we are not gonna land this on any road it will be used for fighting wild fires so say that this was carefully looked at isn't something I believe was done but anyway. This would not be useless at all we are getting a new pack and with that we are gonna get a bunch of wild fire stuff with a wild fire sub division and with that the plane would be very useful for stopping wild fires and will in no means be landed on any road.
