### ISSUE TITLE
Add civillian jobs

### ISSUE THREAD

**Issue by D-Kreiger** [ScottUK/ladojrp-issues#85]
**Describe the feature you'd like implemented**
A clear and concise description of what you want implemented into the server.
I'd like to give civs something to do like passive rp, maybe taxi driving, bus driving working at shops etc and increasing the pay if you do work like- unemployed-500 emplyed-1000 LEO/EMS-2000

**Link to the resource if it already exists**
If it already exists, post the link to the resource here.
N/A
**Additional context**
I think overall this would help passive rp and make people motivated to do better rp than shooting cops and just breaking the law.

**Comment by ladojrp-sourdirt** [comment]
Hello Kreiger this is Sourdirt with the LADOJRP Suggestions team.

Thank you for this suggestion and this will be read very carefully and taken under consideration.

I believe this is a great suggestion and we will look further into this and make a decision on whether to add it. We appreciate the idea of adding more passive rp and ways for people to earn money.

Administrator, Sourdirt

**Comment by ladojrp-sourdirt** [comment]
@ladojrp-alopez ^

**Comment by ladojrp-alopez** [comment]
Hello, I am Lopez, in charge of suggestions being submitted throughout within the community of LADOJRP.

I have reviewed the suggestion and recalled, one of our owners mentioning they were adding jobs soon to the server.

Thanks for the suggestion, 

LADOJRP Suggestions Team
