### ISSUE TITLE
Add a yellow x26 taser for police 

### ISSUE THREAD

**Issue by Turks1** [ScottUK/ladojrp-issues#86]
**Describe the feature you'd like implemented**
A clear and concise description of what you want implemented into the server.
It is the most realistic taser I've seen, and I think it would be a great thing to add

**Link to the resource if it already exists**
If it already exists, post the link to the resource here.
https://www.lcpdfr.com/downloads/gta5mods/misc/9789-taser-x26/

**Additional context**
Nope thanks

**Comment by LADOJRP-Mello** [comment]
We are not looking into adding this, Thanks so much for your suggestion and getting in touch with us!
