### ISSUE TITLE
Priority Script Addon

### ISSUE THREAD

**Issue by CharlieHunter1** [ScottUK/ladojrp-issues#91]
**Describe the feature you'd like implemented**
An addition to the priority script that means the player who is prio is put in brackets next to the prio message because makes it easy to know who prio is.

**Link to the resource if it already exists**
🤷 

**Additional context**
Would help with confusion in this area here? - https://media.discordapp.net/attachments/932330333850964009/932339893600931911/unknown.png

**Comment by LADOJRP-Mello** [comment]
When claiming a priority, Who ever marks priority shall utilize the "Note" option such as:

/setp city inprogress and then put what type of priority it is, and who it is (or the ID)

Departments can add this to there training if all departments like the idea
