### ISSUE TITLE
add docks to the boat house in sandy(im owner of property) 

### ISSUE THREAD

**Issue by Lilderpy041** [ScottUK/ladojrp-issues#97]
https://fivemods.net/product/216/
i think it would be a great way for me to rp with the boat house a lil bit more and i could pay some money if needed

**Comment by LADOJRP-Mello** [comment]
Thanks for your Request, I will ask developers how this would be in-game, As of now I am not sure if payment will be needed to put this in-game or not, or if we can put it in-game at all. Please standby for more updates!

**Comment by ScottUK** [comment]
Sorry but we won't be adding be adding this. :( It takes up performance in a really common area.
